### ISSUE TITLE
Support the UTC formatter in the JSON Reader

### ISSUE THREAD

**Issue by luocooong** [apache/drill#2298]
**Is your feature request related to a problem? Please describe.**
Support the UTC formatter in the JSON Reader

**Describe the solution you'd like**
optional 1 :
- use a few of the most popular formatter and the try-catch
- minimal changes

example :
```java
LocalDateTime ldt;
try {
  OffsetDateTime originalDateTime = OffsetDateTime.parse(parser.getValueAsString(), DateUtility.isoFormatTimeStamp);
  ldt = originalDateTime.toLocalDateTime();
} catch (DateTimeParseException e) {
  ldt = LocalDateTime.parse(parser.getValueAsString(), DateUtility.utcFormatDateTime); // "yyyy-MM-dd'T'HH:mm:ss'Z'"
} catch (DateTimeParseException e) {
  ldt = LocalDateTime.parse(parser.getValueAsString(), DateUtility.utcFormatTimeStamp); // "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
}
OffsetDateTime utcDateTime = OffsetDateTime.of(ldt, ZoneOffset.UTC);
```

optional 2 :
- allow the user to define the UTC formatter use the `ALTER SESSION SET` syntax.
- _not sure the framework support to extend this feature._

example (Dummy) :
```
ALTER SESSION SET `store.json.date_formatter` = "yyyy-MM-dd'T'HH:mm:ss'Z'"
```
```java
LocalDateTime ldt;
if (hasUTCKeyword(parser.getValueAsString()) { // value.indexOf('T') > 0 & value.indexOf('Z') > value.indexOf('T')
  ldt = LocalDateTime.parse(parser.getValueAsString(), session_date_formatter);
} else {
  ldt = OffsetDateTime.parse(parser.getValueAsString(), session_date_formatter).toLocalDateTime();
}
```

**Describe alternatives you've considered**
NONE

**Additional context**

When the date value as the ISODate (without the timezone, or called 0 timezone) store in mongo and set the `store.mongo.bson.record.reader` to false:
```json
{
  "_id" : ObjectId("5da7760149b3f000195cabb"),
  "date" : ISODate("2019-09-24T20:06:56Z")
}
```

Drill got the error stack error :
```
Caused by: java.lang.Exception: Text '2019-09-30T20:47:43Z' could not be parsed at index 19
```

Because the `OffsetDateTime` parse the date string use the fixed formatter `yyyy-MM-dd'T'HH:mm:ss.SSSXX`. Then, the OffsetDateTime is not allowed to accept the UTC formatter `***T***Z` (or called 0 timezone) :
example 1:
```
yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
```
example 2:
```
yyyy-MM-dd'T'HH:mm:ss'Z'
```

Linked resource :
https://github.com/apache/drill/blob/39b565f112122734c080324fdcbef518ced16507/exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/VectorOutput.java#L353-L357

https://github.com/apache/drill/blob/39b565f112122734c080324fdcbef518ced16507/exec/vector/src/main/java/org/apache/drill/exec/expr/fn/impl/DateUtility.java#L635-L635

**Comment by luocooong** [comment]
@paul-rogers @cgivre Look forward to your suggestions.

**Comment by paul-rogers** [comment]
Hi @luocooong,

Thanks for looking at this issue.

It looks like you are modifying the old, obsolete JSON parser. While it is fine to do so, you may want to use the much improved JSON parser in `org.apache.drill.exec.store.easy.json`. Else, we're trying to keep two entirely different code bases in sync. The new version has many, many bug fixes, works with EVF, and supports a provided schema. The new version properly handles Mongo date/time types. The new version, but not the older code, has abundant unit tests. 

What code uses the old version? Should we consider upgrading that code to use the new version?

Here's how things work in the new version.

First, plain JSON has no date-time data type. JSON is limited to string, number, Boolean and null. So, we must be talking about "extended types" for Mongo. We follow two Mongo specs:

* [V1](https://docs.mongodb.com/manual/reference/mongodb-extended-json-v1/#date)
* [V2](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson.Date)

The V2 spec says:

> Relaxed: `{"$date": "<ISO-8601 Date/Time Format>"}` <br/>
> ...  <br/>
> "<ISO-8601 Date/Time Format>"  <br/>
> A date in [ISO-8601 Internet Date/Time Format](https://tools.ietf.org/html/rfc3339#section-5.6) as string.

The class `org.apache.drill.exec.store.easy.json.loader.TestExtendedTypes` tests this functionality. See `testDate()`. This class uses `DateTimeFormatter.ISO_INSTANT` to create a formatted date. The resulting `utc` variable contains the string `"2020-04-21T18:22:33Z"`. The test then verifies that the following "Extended" JSON parses correctly:

```json
{ a: { "$date": "2020-04-21T18:22:33Z" } }
```

Since the only place that date/time is supported in JSON is for the Mongo types, we should follow the Mongo spec for those types. No need to try multiple formats, nor to ask the user for the format. The only formats we should support are those defined by Mongo.

Second, the new version supports a provided schema. It may be that you are working with a JSON file or source witch is not Mongo, yet which includes dates. Simply use the provided schema mechanism to mark the `ts` column (say) as a `TIMESTAMP` and optionally provide a format. The "new" JSON parser will automagically do the conversion.

Where are you using the old JSON parser?

**Comment by cgivre** [comment]
@paul-rogers Do you think we should explicitly mark the old reader as deprecated?

**Comment by paul-rogers** [comment]
@cgivre, we could deprecate the old version. A quick dependency check suggests the old version is still used by Mongo, the metastore and Kafka. To deprecate the old version we'd have to update those three usages (at least).

In the meantime, we could add a comment in the code suggesting new code use the newer version.

**Comment by luocooong** [comment]
@paul-rogers Well. I've confirmed that it's really old. Thanks for the tips.
Oddly, I may have used the old package `org.apache.drill.exec.store.json` and the test class `TestJsonRecordReader`. But the error stack log show that does not apply the new JSON loader?
```java
Caused by: java.time.format.DateTimeParseException: Text '2019-09-30T20:47:43Z' could not be parsed at index 19
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.OffsetDateTime.parse(OffsetDateTime.java:402)
	at org.apache.drill.exec.vector.complex.fn.VectorOutput$MapVectorOutput.writeTimestamp(VectorOutput.java:354)
	at org.apache.drill.exec.vector.complex.fn.VectorOutput.innerRun(VectorOutput.java:113)
	at org.apache.drill.exec.vector.complex.fn.VectorOutput$MapVectorOutput.run(VectorOutput.java:302)
	at org.apache.drill.exec.vector.complex.fn.JsonReader.writeMapDataIfTyped(JsonReader.java:386)
	at org.apache.drill.exec.vector.complex.fn.JsonReader.writeData(JsonReader.java:262)
	at org.apache.drill.exec.vector.complex.fn.JsonReader.writeDataSwitch(JsonReader.java:192)
	at org.apache.drill.exec.vector.complex.fn.JsonReader.writeDocument(JsonReader.java:178)
	at org.apache.drill.exec.store.easy.json.reader.BaseJsonReader.writeToVector(BaseJsonReader.java:99)
	at org.apache.drill.exec.store.easy.json.reader.BaseJsonReader.write(BaseJsonReader.java:70)
	at org.apache.drill.exec.store.mongo.MongoRecordReader.next(MongoRecordReader.java:203)
	at org.apache.drill.exec.physical.impl.ScanBatch.internalNext(ScanBatch.java:234)
	at org.apache.drill.exec.physical.impl.ScanBatch.next(ScanBatch.java:298)
	... 18 common frames omitted
```

**Comment by paul-rogers** [comment]
Hi @luocooong, as it turns out, the stack trace shows the old JSON reader. The key is the package: `org.apache.drill.exec.vector.complex.fn.JsonReader`. The new one is in `org.apache.drill.exec.store.easy.json`.

The old one was meant to be an independent module, it seems, part of the Value Vector package. The new one builds on top of the vector accessors and EVF.

The key limitation of the old one (aside from the date issue you hit) is that the old one has no notion of vector sizes. It is based on a fixed record count. If your records are big, the old one will allocate an excessive amount of direct memory. In an extreme case, it can allocate vectors in excess of 16GB, which will cause direct memory fragmentation and eventual OOM errors. The memory issue was the original reason for building the vector accessor mechanism which is the heart of the EVF.

Now, I'm sure you just need the Mongo reader to work and are not tasked with revising it to use the new JSON parser. So, a temporary solution is simply to ensure that the old reader follows the same Mongo date/time specs as the new reader does. Links to the Mongo specs are in the note above.

**Comment by luocooong** [comment]
@paul-rogers Thanks for the information. But the old JSON loader use the fixed date formatter : `yyyy-MM-dd'T'HH:mm:ss.SSSXX`, It required a timezone (or offset). And then, the OffsetDateTime class does not accept a date string without timezone.

https://github.com/apache/drill/blob/39b565f112122734c080324fdcbef518ced16507/exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/VectorOutput.java#L353-L354

So, the old JSON loader cannot parse the `2019-09-30T20:47:43Z`(with this fixed formatter). Interestingly, the `2019-09-30T20:47:43Z` is equals to the `2019-09-30T20:47:43+0000` (`Z` is the 0 timezone), but the OffsetDateTime don't even know it. 
In this case, Do we need to update the new JSON loader?

**Comment by paul-rogers** [comment]
@luocooong, I may be confused, but as I read the Mongo spec, it does want the UTC "Zulu" format: `2019-09-30T20:47:43Z`. I verified that this format is tested and does work correctly in the new JSON loader.

When you say "without a timezone", I think you are describing a date/time of the form `2019-09-30T20:47:43`. Ths would be a local time. Drill uses local time internally, but Mongo (wisely) seems to use UTC time. Thus, if you are reading Mongo data, you should not see a local time (if I understand Mongo correctly.) By the way, `2019-09-30T20:47:43Z` does have a time zone: it is zero offset, also called GMT.

Looks like your testing shows that the "Zulu" format is broken in the old JSON parser. I don't know why the code might have used the format you described. That format does not seem to match the Mongo spec. Perhaps the original author was trying to match some other version?

I looked at the code in your call stack. It is pretty convoluted -- another reason for the new JSON parser. The JSON parser tries to handle all maps the same. Mongo extended types are, syntactically, a JSON map. The `MapVectorOutput.run()` method checks for Mongo keywords. For the date/time keyword, the code then calls `VectorOutput$MapVectorOutput.writeTimestamp`. I suspect this is where things went wrong. The `VectorOutput$MapVectorOutput.writeTimestamp` method is not unique to Mongo JSON, it is a generic vector method. As you note, at present it uses the `isoFormatTime` constant in `DateUtility`:

```java
  public static final DateTimeFormatter isoFormatTime     = buildFormatter("HH:mm:ss.SSSXX");
```

For Mongo, it should use the `UTC_FORMATTER` constant:

```java
  public static final DateTimeFormatter UTC_FORMATTER = buildFormatter("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
```

Checking the file history, it looks like the following commit broke things: "DRILL-6242 Use java.time.Local{Date|Time|DateTime} for Drill Date, Time, Timestamp types." (Use "Blame" on the `VectorOutput.java` file.) My guess is that the author wanted to make sure Drill used only local times, and did not realize that he was breaking Mongo which requires ISO "Zulu" timestamps.

A quick check of the code suggests that only the old `JsonReader` uses this code path. So, you can try reverting the code to use the `UTC_FORMATTER` and rerun unit tests. Also check against your Mongo test case. If both of these work, then this is the simplest fix.

Now, it could be that something in the tests uses a Mongo-format date/time, but with a Drill-like local time. If so, then we can look at the problem an think about how to solve it. Let's see if running the tests tells us if we even have this problem.
