### ISSUE TITLE
Missing 1.20.1 Release

### ISSUE THREAD

**Issue by ankane** [apache/drill#2614]
**Describe the bug**

Hi, it looks like Drill 1.20.1 was released on May 16 according to [this post](https://drill.apache.org/blog/2022/05/16/drill-1.20.1-released/) and the [release notes](https://drill.apache.org/docs/apache-drill-1-20-1-release-notes/), and Homebrew picked up a release on that date (https://github.com/Homebrew/homebrew-core/pull/101694).

However:

- the [download page](https://drill.apache.org/download/) points to 1.20.0
- it's not available on [mirrors](https://www.apache.org/dyn/closer.lua?path=drill/drill-1.20.1/apache-drill-1.20.1.tar.gz)
- it's not available in [the archive](https://archive.apache.org/dist/drill/)
- it's not listed under "Releases" on GitHub (but is tagged)

**Comment by jnturton** [comment]
Thank you for opening this. You're right that we're currently missing our 1.20.1 build due to some technical reasons but the good news is that we're just about to put up a 1.20.2 build. If you'd like to play with the first release candidate (which won't be promoted to a release, but only due to some issues relating to legacy Hadoop 2 support) then have a look here.

https://dist.apache.org/repos/dist/dev/drill/1.20.2-rc0/

**Comment by ankane** [comment]
Thanks @jnturton
